/*
 * NOCTURNE_OS — Config: pins (SDA/SCL/RST), display 128x64, timeouts,
 * NOCT_SCENE_* indices, NOCT_GRAPH_SAMPLES. WiFi/PC IP in secrets.h.
 */
#ifndef NOCTURNE_CONFIG_H
#define NOCTURNE_CONFIG_H

#define NOCT_SDA_PIN 17
#define NOCT_SCL_PIN 18
#define NOCT_RST_PIN 21
#define NOCT_VEXT_PIN 36
#define NOCT_LED_PIN 35
#define NOCT_BUTTON_PIN 0

#define NOCT_DISP_W 128
#define NOCT_DISP_H 64
#define NOCT_MARGIN 2
#define NOCT_HEADER_H 9 /* Grid: header 0..8, dotted line at Y=9 */
#define NOCT_FOOTER_Y 50
#define NOCT_LINE_H_DATA 12
#define NOCT_LINE_H_LABEL 5
#define NOCT_LINE_H_HEAD 10
#define NOCT_LINE_H_BIG 14
#define NOCT_TCP_LINE_MAX 4096
#define NOCT_TCP_CONNECT_TIMEOUT_MS 5000
#define NOCT_TCP_RECONNECT_INTERVAL_MS 2000
#define NOCT_SIGNAL_TIMEOUT_MS 5000
#define NOCT_SIGNAL_GRACE_MS 8000
#define NOCT_WIFI_RETRY_INTERVAL_MS 30000
#define NOCT_SPLASH_MS 2000
#define NOCT_BUTTON_SHORT_MS 500
#define NOCT_BUTTON_LONG_MS 1000
#define NOCT_BUTTON_PREDATOR_MS 2500
#define NOCT_GLITCH_INTERVAL_MS 10000 /* Glitch once every 10s, subtle */
#define NOCT_GLITCH_DURATION_MS 100
#define NOCT_GRAPH_SAMPLES 32 /* Lower = less RAM; 32 enough for sparkline */
#define NOCT_GRAPH_HEIGHT 11

/* RED ALERT thresholds (must match monitor.py) */
#ifndef CPU_TEMP_ALERT
#define CPU_TEMP_ALERT 87
#endif
#ifndef GPU_TEMP_ALERT
#define GPU_TEMP_ALERT 68
#endif
#define CPU_LOAD_ALERT 99
#define GPU_LOAD_ALERT 99
#define VRAM_LOAD_ALERT 95

/* 5 screens: THERMAL, LOAD, MEMORY, STORAGE, FANS (brutalist monitoring) */
#define NOCT_SCENE_THERMAL 0
#define NOCT_SCENE_LOAD 1
#define NOCT_SCENE_MEMORY 2
#define NOCT_SCENE_STORAGE 3
#define NOCT_SCENE_FANS 4
#define NOCT_TOTAL_SCENES 5
/* Legacy aliases for code that still references old names */
#define NOCT_SCENE_HUB NOCT_SCENE_THERMAL
#define NOCT_SCENE_CPU NOCT_SCENE_THERMAL
#define NOCT_SCENE_GPU NOCT_SCENE_LOAD
#define NOCT_SCENE_RAM NOCT_SCENE_MEMORY
#define NOCT_SCENE_DISKS NOCT_SCENE_STORAGE
#define NOCT_SCENE_ATMOS NOCT_SCENE_THERMAL
#define NOCT_SCENE_MEDIA NOCT_SCENE_THERMAL

#endif
