/*
 * NOCTURNE_OS — Config (pins, dimensions). Secrets in secrets.h
 */
#ifndef NOCTURNE_CONFIG_H
#define NOCTURNE_CONFIG_H

#define NOCT_SDA_PIN 17
#define NOCT_SCL_PIN 18
#define NOCT_RST_PIN 21
#define NOCT_VEXT_PIN 36
#define NOCT_LED_PIN 35
#define NOCT_BUTTON_PIN 0

#define NOCT_DISP_W 128
#define NOCT_DISP_H 64
#define NOCT_MARGIN 2
#define NOCT_HEADER_H 10
#define NOCT_FOOTER_Y 50
#define NOCT_LINE_H_DATA 12
#define NOCT_LINE_H_LABEL 5
#define NOCT_LINE_H_HEAD 10
#define NOCT_LINE_H_BIG 14
#define NOCT_TCP_LINE_MAX 4096
#define NOCT_TCP_CONNECT_TIMEOUT_MS 5000
#define NOCT_TCP_RECONNECT_INTERVAL_MS 2000
#define NOCT_SIGNAL_TIMEOUT_MS 5000
#define NOCT_SIGNAL_GRACE_MS 8000
#define NOCT_WIFI_RETRY_INTERVAL_MS 30000
#define NOCT_SPLASH_MS 2000
#define NOCT_BUTTON_SHORT_MS 500
#define NOCT_BUTTON_LONG_MS 1000
#define NOCT_BUTTON_PREDATOR_MS 2500
#define NOCT_GLITCH_INTERVAL_MS 60000
#define NOCT_GLITCH_DURATION_MS 100
#define NOCT_GRAPH_SAMPLES 64
#define NOCT_GRAPH_HEIGHT 11

#ifndef CPU_TEMP_ALERT
#define CPU_TEMP_ALERT 75
#endif
#ifndef GPU_TEMP_ALERT
#define GPU_TEMP_ALERT 80
#endif

#define NOCT_SCENE_HUB 0
#define NOCT_SCENE_CPU 1
#define NOCT_SCENE_GPU 2
#define NOCT_SCENE_NET 3
#define NOCT_SCENE_ATMOS 4
#define NOCT_SCENE_MEDIA 5
#define NOCT_TOTAL_SCENES 6

#endif
